name: Import Issues from CSV

on:
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  import-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install pandas requests

      - name: Run CSV Import Script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          python3 <<EOF
import pandas as pd
import requests
import os

csv_path = 'mood_music_backlog.csv'  # adjust if in subfolder
df = pd.read_csv(csv_path)

repo = os.environ['REPO']
token = os.environ['GH_TOKEN']
api_url = f'https://api.github.com/repos/{repo}/issues'
headers = {'Authorization': f'token {token}'}

for _, row in df.iterrows():
    title = row['Title']
    body = f"**Description:** {row['Description']}\n\n**Sprint:** {row['Sprint']}\n**Type:** {row['Type']}\n**Priority:** {row['Priority']}"
    payload = {'title': title, 'body': body}
    response = requests.post(api_url, json=payload, headers=headers)
    if response.status_code != 201:
        print(f"Failed to create issue: {title} - {response.status_code}: {response.text}")
    else:
        print(f"Issue created: {title}")
EOF
